-- MySQL Script generated by MySQL Workbench
-- Thu Jan 31 14:48:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ArticleSearch
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Schema ArticleSearch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ArticleSearch` DEFAULT CHARACTER SET utf8 ;
USE `ArticleSearch` ;

-- -----------------------------------------------------
-- Table `ArticleSearch`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArticleSearch`.`user_role` ;

CREATE TABLE IF NOT EXISTS `ArticleSearch`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArticleSearch`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArticleSearch`.`article` ;

CREATE TABLE IF NOT EXISTS `ArticleSearch`.`article` (
  `art_id` INT NOT NULL AUTO_INCREMENT,
  `art_title` VARCHAR(255) NULL,
  `art_desc` VARCHAR(1000) NULL,
  `art_content` VARCHAR(5000) NULL,
  `art_author` VARCHAR(70) NULL,
  `art_url` VARCHAR(255) NULL,
  `art_urlToImage` VARCHAR(255) NULL,
  `art_publishedat` VARCHAR(50) NULL,
  PRIMARY KEY (`art_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArticleSearch`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArticleSearch`.`language` ;

CREATE TABLE IF NOT EXISTS `ArticleSearch`.`language` (
  `lang_id` INT NOT NULL AUTO_INCREMENT,
  `lang_name` VARCHAR(45) NULL,
  `lang_code` VARCHAR(10) NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArticleSearch`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArticleSearch`.`user` ;

CREATE TABLE IF NOT EXISTS `ArticleSearch`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(70) NOT NULL,
  `us_email` VARCHAR(45) NOT NULL,
  `us_password` VARCHAR(255) NOT NULL,
  `us_ur_id` INT NOT NULL,
  `us_art_id` INT NULL,
  `us_lang_id` INT NULL,
  `us_status` VARCHAR(15) NULL,
  PRIMARY KEY (`us_id`),
  INDEX `us_ur_id_idx` (`us_ur_id` ASC),
  INDEX `us_art_id_idx` (`us_art_id` ASC),
  INDEX `us_lang_id_idx` (`us_lang_id` ASC),
  CONSTRAINT `us_ur_id`
    FOREIGN KEY (`us_ur_id`)
    REFERENCES `ArticleSearch`.`user_role` (`ur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `us_art_id`
    FOREIGN KEY (`us_art_id`)
    REFERENCES `ArticleSearch`.`article` (`art_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `us_lang_id`
    FOREIGN KEY (`us_lang_id`)
    REFERENCES `ArticleSearch`.`language` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ArticleSearch`.`favourite_article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ArticleSearch`.`favourite_article` ;

CREATE TABLE IF NOT EXISTS `ArticleSearch`.`favourite_article` (
  `fa_id` INT NOT NULL AUTO_INCREMENT,
  `fa_art_id` INT NOT NULL,
  `fa_us_id` INT NULL,
  PRIMARY KEY (`fa_id`),
  INDEX `favart_art_id_idx` (`fa_art_id` ASC),
  CONSTRAINT `favart_art_id`
    FOREIGN KEY (`fa_art_id`)
    REFERENCES `ArticleSearch`.`article` (`art_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
